### PR TITLE
Need to review before merge from official.

### PR DESCRIPTION
**Pull request by Apaisal**
local develop branch sync with official on 20240911
and need to review before merge into next aiim version.

### CODE REVIEW

**Comment by ttip-ts** [comment]
Hello, my name is Namthip. 
1. I am an assistant researcher from the AIIM team. I am encountering an issue with viewing data in the OpenMCT system. The screenshot displays a message "Missing: taxonomy.spacecraft" on the left panel, which might indicate that the system is unable to retrieve or display data from the RPi5 5 cameras. Additionally, I am viewing a folder named "My Items," which also appears to contain no data. I would like instructions or a user manual on how to activate or use OpenMCT to view the data from the RPi5 5 cameras.
IMG_2773


2. I would like to know how to monitor the heartbeat in the MobaXterm program.
IMG_2775

**Comment by Apaisal** [comment]
Hi @ttip-ts ,

Thank you for your report.

> 1. OpenMCT "Missing: taxonomy.spacecraft"

1. Have you check YAMCS is working? Because OpenMCT has openmct-yamcs plugin to retrieve data from YAMCS API.
2. Camera streaming from the device by mediamtx, Please check mediamtx service on your device.
3. Getting started guide and learning below tools

- https://github.com/EmOne/yamcs-quickstart
- https://github.com/EmOne/openmct
- https://github.com/EmOne/openmct-yamcs
- https://github.com/emone/mediamtx

> 2\. Monitor the heartbeat in the MobaXterm program or any console.

1. You must learn how to access the device via SSH client.
2. On device has can-utils tool to observe and dump CAN messages what you need.

-  https://github.com/EmOne/can-utils

BTW, To avoid complex analysis and multi-issues on a comment 
Please analyze your issues before any comments and open issue following specific tool related.
Thank you in advance.

**Comment by ttip-ts** [comment]
Hi Mr.Anol @Apaisal 
Could you please provide me with the password for the Raspberry Pi?
IMG_1764

I clicked to shut down the laptop, and the YAMCS web page disconnected.
IMG_1765

**Comment by Apaisal** [comment]
Hi @ttip-ts 

> you please provide me with the password for the Raspberry Pi?

This is very sensitive information, Please take a look the default password from community.

> I clicked to shut down the laptop, and the YAMCS web page disconnected.

This scenario related YAMCS. Please see YAMCS repository for learning.

BTW, please discuss on CRA-AIIM backlog at [CRA-AIIM](https://github.com/orgs/EmOne/projects/6/views/1)

**Pull request merged**
